/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Inkporter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  outputDirectory: "FieldNotes",
  alphaThreshold: 180,
  fileNameTemplate: "field-note-{date}-{shortId}",
  convertToGrayscale: false,
  useLuminosityForAlpha: true
};
var Inkporter = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "inkporter",
      name: "Inkporter",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "v" }],
      callback: async () => {
        try {
          const processed = await this.processClipboardContent();
          if (processed) {
            new PreviewModal(this.app, processed, (confirmed) => {
              if (confirmed)
                this.saveAndInsertImage(processed);
            }).open();
          }
        } catch (error) {
          this.handleError(error);
        }
      }
    });
    this.addSettingTab(new InkporterSettingsTab(this.app, this));
  }
  async processClipboardContent() {
    try {
      const clipboardItems = await navigator.clipboard.read();
      for (const item of clipboardItems) {
        for (const type of item.types) {
          if (type.startsWith("image/")) {
            const blob = await item.getType(type);
            return this.processImage(await blob.arrayBuffer());
          }
        }
      }
      throw new Error("No image found in clipboard");
    } catch (error) {
      if (error instanceof DOMException && error.name === "NotAllowedError") {
        new import_obsidian.Notice("Clipboard access denied. Please enable clipboard permissions.");
      } else {
        this.handleError(error);
      }
      return null;
    }
  }
  async processImage(buffer) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext("2d", { willReadFrequently: true });
        if (!ctx) {
          reject(new Error("Could not create canvas context"));
          return;
        }
        ctx.drawImage(img, 0, 0);
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imageData.data;
        this.processPixels(data);
        ctx.putImageData(imageData, 0, 0);
        canvas.toBlob(async (blob) => {
          if (!blob) {
            reject(new Error("Failed to convert canvas to blob"));
            return;
          }
          resolve({
            buffer: await blob.arrayBuffer(),
            fileName: this.generateFileName()
          });
        }, "image/png");
      };
      img.onerror = () => reject(new Error("Failed to load image"));
      img.src = URL.createObjectURL(new Blob([buffer]));
    });
  }
  processPixels(data) {
    for (let i = 0; i < data.length; i += 4) {
      const r = data[i];
      const g = data[i + 1];
      const b = data[i + 2];
      const brightness = this.settings.useLuminosityForAlpha ? 0.299 * r + 0.587 * g + 0.114 * b : (r + g + b) / 3;
      if (this.settings.convertToGrayscale) {
        data[i] = data[i + 1] = data[i + 2] = brightness;
      }
      data[i + 3] = brightness <= this.settings.alphaThreshold ? 255 : 0;
    }
  }
  generateFileName() {
    const now = new Date();
    const dateString = now.toISOString().slice(0, 10).replace(/-/g, "");
    const shortId = self.crypto.randomUUID().slice(0, 8);
    return this.settings.fileNameTemplate.replace("{timestamp}", Date.now().toString()).replace("{date}", dateString).replace("{shortId}", shortId).replace("{uuid}", self.crypto.randomUUID());
  }
  async saveAndInsertImage(image) {
    try {
      const outputDir = (0, import_obsidian.normalizePath)(this.settings.outputDirectory);
      const filePath = `${outputDir}/${image.fileName}.png`;
      if (!await this.app.vault.adapter.exists(outputDir)) {
        await this.app.vault.createFolder(outputDir);
      }
      await this.app.vault.adapter.writeBinary(filePath, image.buffer);
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView) {
        activeView.editor.replaceSelection(`![[/${filePath}]]`);
      }
    } catch (error) {
      this.handleError(error);
    }
  }
  handleError(error) {
    const message = error instanceof Error ? error.message : "Unknown error occurred";
    new import_obsidian.Notice(`Inkporter Error: ${message}`);
    console.error(error);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, image, callback) {
    super(app);
    this.image = image;
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("Inkporter-modal");
    contentEl.createEl("h2", { text: "Preview Processed Image" });
    this.objectUrl = URL.createObjectURL(new Blob([this.image.buffer]));
    const img = contentEl.createEl("img", {
      attr: { src: this.objectUrl, alt: "Processed image preview" },
      cls: "Inkporter-preview-image"
    });
    img.style.maxWidth = "100%";
    img.style.height = "auto";
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Insert").setCta().onClick(() => {
      this.callback(true);
      this.close();
    })).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.callback(false);
      this.close();
    }));
  }
  onClose() {
    URL.revokeObjectURL(this.objectUrl);
  }
};
var InkporterSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output directory").setDesc("Where to store processed images").addText((text) => text.setValue(this.plugin.settings.outputDirectory).onChange(async (value) => {
      this.plugin.settings.outputDirectory = value;
      await this.plugin.saveSettings();
    }));
    const alphaSetting = new import_obsidian.Setting(containerEl).setName("Alpha threshold").setDesc("Pixels darker than this value will become opaque (0-255)");
    let sliderComponent;
    let textComponent;
    alphaSetting.addSlider((slider) => {
      sliderComponent = slider;
      slider.setLimits(0, 255, 1).setValue(this.plugin.settings.alphaThreshold).onChange(async (value) => {
        this.plugin.settings.alphaThreshold = value;
        await this.plugin.saveSettings();
        textComponent.setValue(value.toString());
      }).setDynamicTooltip();
    });
    alphaSetting.addText((text) => {
      textComponent = text;
      text.setValue(this.plugin.settings.alphaThreshold.toString()).setPlaceholder("0-255").onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0 && num <= 255) {
          this.plugin.settings.alphaThreshold = num;
          await this.plugin.saveSettings();
          sliderComponent.setValue(num);
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("File name template").setDesc("Available placeholders: {timestamp}, {date}, {shortId}, {uuid}").addText((text) => text.setValue(this.plugin.settings.fileNameTemplate).onChange(async (value) => {
      this.plugin.settings.fileNameTemplate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Convert to grayscale").setDesc("Convert image to grayscale before processing").addToggle((toggle) => toggle.setValue(this.plugin.settings.convertToGrayscale).onChange(async (value) => {
      this.plugin.settings.convertToGrayscale = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Use luminosity for alpha").setDesc("Use luminosity (perceptual brightness) for alpha calculation").addToggle((toggle) => toggle.setValue(this.plugin.settings.useLuminosityForAlpha).onChange(async (value) => {
      this.plugin.settings.useLuminosityForAlpha = value;
      await this.plugin.saveSettings();
    }));
  }
};


/* nosourcemap */